const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));

function updateBrandLogo(){
  const img=document.querySelector('[data-brand-logo]');
  if(!img)return;
  const light=img.getAttribute('data-logo-light')||img.src;
  const dark=img.getAttribute('data-logo-dark')||light;
  const isDark=getTheme()==='dark';
  img.src=isDark?dark:light;
}

function setTheme(t){document.documentElement.setAttribute('data-theme',t==='dark'?'dark':'');localStorage.setItem('theme',t);updateBrandLogo()}
function getTheme(){const s=localStorage.getItem('theme');if(s)return s;return window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
function toggleTheme(){setTheme(getTheme()==='dark'?'light':'dark')}
setTheme(getTheme());

function smoothScrollTo(el){const r=el.getBoundingClientRect();const o=window.scrollY+r.top-(parseInt(getComputedStyle(document.documentElement).scrollPaddingTop)||0);window.scrollTo({top:o,behavior:'smooth'})}
function handleAnchors(e){const a=e.target.closest('a[href^="#"]');if(!a||a.getAttribute('href')==='#')return;const id=a.getAttribute('href').slice(1);const t=document.getElementById(id);if(!t)return;e.preventDefault();smoothScrollTo(t);history.pushState(null,'',`#${id}`)}
function headerScrollState(){const y=window.scrollY||document.documentElement.scrollTop;$$('.header,.nav').forEach(n=>n&&n.classList.toggle('is-scrolled',y>12))}
function revealOnScroll(){const io=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-inview');io.unobserve(e.target)}})},{threshold:.15});$$('.reveal').forEach(el=>io.observe(el))}
function progressInView(){const bars=$$('.progress[data-value]');if(!bars.length)return;const io=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){const v=e.target.getAttribute('data-value')||'0';const bar=e.target.querySelector('.progress__bar');if(bar){requestAnimationFrame(()=>{bar.style.width=Math.max(0,Math.min(100,Number(v)))+'%'})}io.unobserve(e.target)}})},{threshold:.3});bars.forEach(b=>io.observe(b))}
function tabsInit(){$$('.tabs').forEach(group=>{group.addEventListener('click',e=>{const t=e.target.closest('.tab[data-target]');if(!t)return;const sel=t.dataset.target;const allTabs=Array.from(group.querySelectorAll('.tab[data-target]'));allTabs.forEach(x=>x.classList.remove('tab--active'));t.classList.add('tab--active');const panels=allTabs.map(x=>x.dataset.target).map(s=>document.querySelector(s)).filter(Boolean);panels.forEach(p=>{p.style.display='none';p.setAttribute('aria-hidden','true')});const panel=document.querySelector(sel);if(panel){panel.style.display='';panel.removeAttribute('aria-hidden')}})})}
function accordionSingle(){$$('.accordion[data-single="true"]').forEach(acc=>{acc.addEventListener('toggle',e=>{const d=e.target;if(!(d instanceof HTMLDetailsElement))return;if(!d.open)return;acc.querySelectorAll('details').forEach(x=>{if(x!==d)x.open=false})},true)})}
function cardTilt(){const items=$$('.card--interactive .card__tilt');items.forEach(el=>{const p=el.parentElement;let a=null;function mv(e){const r=el.getBoundingClientRect();const x=((e.clientX-r.left)/r.width)-.5;const y=((e.clientY-r.top)/r.height)-.5;el.style.transform=`rotateX(${(-y*6).toFixed(2)}deg) rotateY(${(x*6).toFixed(2)}deg) translateZ(0)`;if(a)cancelAnimationFrame(a)}function out(){a=requestAnimationFrame(()=>{el.style.transform='rotateX(0deg) rotateY(0deg) translateZ(0)'})}p.addEventListener('mousemove',mv);p.addEventListener('mouseleave',out);p.addEventListener('touchmove',e=>{const t=e.touches[0];mv(t)},{passive:true});p.addEventListener('touchend',out)})}
function showToast(message,type='info',duration=3500){const t=document.createElement('div');t.className='toast';t.innerHTML=`<div>${message}</div>`;document.body.appendChild(t);setTimeout(()=>{t.style.transform='translateY(0)'},10);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(10px)';setTimeout(()=>t.remove(),300)},duration);return t}
function modalInit(){document.addEventListener('click',e=>{const o=e.target.closest('[data-modal-open]');if(o){const id=o.getAttribute('data-modal-open');const m=document.querySelector(`[data-modal="${id}"]`);if(m){m.style.display='grid';setTimeout(()=>m.classList.add('open'),10)}}const c=e.target.closest('[data-modal-close]');if(c){const m=c.closest('[data-modal]');if(m){m.classList.remove('open');setTimeout(()=>{m.style.display='none'},200)}}const bg=e.target.closest('[data-modal]');if(bg&&e.target===bg){bg.classList.remove('open');setTimeout(()=>{bg.style.display='none'},200)}})}
function themeControls(){$$( '[data-theme-toggle]' ).forEach(b=>b.addEventListener('click',()=>{toggleTheme();updateBrandLogo()}));$$( '.switch[data-switch="theme"]' ).forEach(sw=>{const sync=()=>sw.dataset.on=String(getTheme()==='dark');sync();sw.addEventListener('click',()=>{toggleTheme();sync();updateBrandLogo()})});window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',e=>{if(!localStorage.getItem('theme')) {setTheme(e.matches?'dark':'light');updateBrandLogo()}});document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='t'&&(e.ctrlKey||e.metaKey)){toggleTheme();updateBrandLogo()}})}
function scrollSpy(){const links=$$('a[href^="#"]');const secs=links.map(l=>document.getElementById(l.getAttribute('href').slice(1))).filter(Boolean);if(!secs.length)return;const io=new IntersectionObserver(es=>{es.forEach(x=>{if(x.isIntersecting){const id=x.target.id;links.forEach(a=>a.removeAttribute('aria-current'));links.filter(a=>a.getAttribute('href')===`#${id}`).forEach(a=>a.setAttribute('aria-current','page'))}})},{rootMargin:'-40% 0% -55% 0%'});secs.forEach(s=>io.observe(s))}
function copyActions(){document.addEventListener('click',e=>{const btn=e.target.closest('[data-copy-target]');if(!btn)return;const sel=btn.getAttribute('data-copy-target');const el=document.querySelector(sel);if(!el)return;const val=(el.value??el.textContent??'').toString().trim();if(!val)return;navigator.clipboard.writeText(val).then(()=>showToast('Copied','info',2000))})}
function formEnhance(){document.addEventListener('submit',e=>{const f=e.target.closest('form[data-enhance]');if(!f)return;e.preventDefault();const btn=f.querySelector('button[type="submit"],.btn-primary');if(btn){btn.disabled=true;btn.style.opacity='.8'}setTimeout(()=>{showToast('Submitted');if(btn){btn.disabled=false;btn.style.opacity='1'}f.reset()},900)})}
function anchorInit(){document.addEventListener('click',handleAnchors)}
function autoActiveYear(){$$('.year-now').forEach(el=>el.textContent=new Date().getFullYear())}
function animateCounters(){const items=$$('[data-count-to]');if(!items.length)return;const io=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){const el=e.target;const to=parseFloat(el.getAttribute('data-count-to'))||0;const dur=parseInt(el.getAttribute('data-count-dur')||'1200',10);const start=performance.now();const from=parseFloat(el.textContent)||0;function step(t){const p=Math.min(1,(t-start)/dur);const v=from+(to-from)*(1- Math.pow(1-p,3));el.textContent=Math.round(v).toLocaleString();if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step);io.unobserve(el)}})},{threshold:.6});items.forEach(el=>io.observe(el))}
function init(){headerScrollState();window.addEventListener('scroll',headerScrollState,{passive:true});revealOnScroll();progressInView();tabsInit();accordionSingle();cardTilt();modalInit();themeControls();scrollSpy();copyActions();formEnhance();anchorInit();autoActiveYear();animateCounters();updateBrandLogo();document.body.classList.add('js-ready')}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init)}else{init()}
